name: sih_23_audiometer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  audio_streamer: ^4.0.0
  audioplayers: ^5.2.1
  audioplayers_web: ^4.1.0
  cupertino_icons: ^1.0.2
  datetime_picker_formfield_new: ^2.1.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  flutter_test:
    sdk: flutter
  google_fonts: ^6.1.0
  headset_connection_event: ^3.1.0
  volume_watcher: ^2.0.1
  perfect_volume_control: ^1.0.5
  noise_meter: ^5.0.2
  permission_handler: ^11.1.0
  syncfusion_flutter_charts: ^23.2.7
  url_launcher: ^6.2.2
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets\audio\tone.mp3
    - assets\images\abhi.png
    - assets\images\login.jpg
    - assets\images\signup.png
    - assets\images\bluetooth.png
    - assets\images\headphone.png
    - assets\images\eduapp_student_login.jpg
    - assets\images\admin.png
    - assets\images\leftear.png
    - assets\images\rightear.png
    - assets\images\eduapp_student_login.jpg
    - assets\audio\250hz.mp3
    - assets\audio\500hz.mp3
    - assets\audio\1000hz.mp3
    - assets\audio\2000hz.mp3
    - assets\audio\4000hz.mp3
    - assets\audio\8000hz.mp3
    - assets\images\bluecrossgraph.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
