name: sih_23_audiometer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  audio_streamer: ^4.0.0
  audioplayers: ^5.2.1
  audioplayers_web: ^4.1.0
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  datetime_picker_formfield_new: ^2.1.0
  dialog_flowtter: ^0.3.3
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  google_fonts: 4.0.4
  google_sign_in: ^6.2.1
  headset_connection_event: ^3.1.0
  microphone: ^0.1.0
  noise_meter: ^5.0.2
  perfect_volume_control: ^1.0.5
  permission_handler: ^11.1.0
  syncfusion_flutter_charts: ^23.2.7
  url_launcher: ^6.2.2
  velocity_x: ^4.1.2
  volume_watcher: ^2.0.1
  localization: ^2.1.1
  get: ^4.6.6
  syncfusion_flutter_pdf: ^23.2.7
  path_provider: ^2.1.1
  open_file: ^3.3.2
dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets\dialog_flow_auth.json
    - assets\audio\tone.mp3
    - assets\images\abhi.png
    - assets\images\login.jpg
    - assets\images\signup.png
    - assets\images\bluetooth.png
    - assets\images\headphone.png
    - assets\images\admin.png
    - assets\images\leftear.png
    - assets\images\rightear.png
    - assets\images\student.jpg
    - assets\audio\250hz.mp3
    - assets\audio\500hz.mp3
    - assets\audio\1000hz.mp3
    - assets\audio\2000hz.mp3
    - assets\audio\4000hz.mp3
    - assets\images\eduapp_student_login.jpg
    - assets\audio\8000hz.mp3
    - assets\images\bluecrossgraph.png
    - assets\images\baground.jpg
    - assets\images\admin.png
    - assets\images\notick.png
    - assets\images\yestick.png
    - assets\images\logo.png

    - assets\leftear\hearingTest.online.warble_250_10_L.mp3
    - assets\leftear\hearingTest.online.warble_250_20_L.mp3
    - assets\leftear\hearingTest.online.warble_250_30_L.mp3
    - assets\leftear\hearingTest.online.warble_250_40_L.mp3
    - assets\leftear\hearingTest.online.warble_250_50_L.mp3
    - assets\leftear\hearingTest.online.warble_250_60_L.mp3
    - assets\leftear\hearingTest.online.warble_250_70_L.mp3
    - assets\leftear\hearingTest.online.warble_250_80_L.mp3

    - assets\leftear\hearingTest.online.warble_500_10_L.mp3
    - assets\leftear\hearingTest.online.warble_500_20_L.mp3
    - assets\leftear\hearingTest.online.warble_500_30_L.mp3
    - assets\leftear\hearingTest.online.warble_500_40_L.mp3
    - assets\leftear\hearingTest.online.warble_500_50_L.mp3
    - assets\leftear\hearingTest.online.warble_500_60_L.mp3
    - assets\leftear\hearingTest.online.warble_500_70_L.mp3
    - assets\leftear\hearingTest.online.warble_500_80_L.mp3

    - assets\leftear\hearingTest.online.warble_1000_10_L.mp3
    - assets\leftear\hearingTest.online.warble_1000_20_L.mp3
    - assets\leftear\hearingTest.online.warble_1000_30_L.mp3
    - assets\leftear\hearingTest.online.warble_1000_40_L.mp3
    - assets\leftear\hearingTest.online.warble_1000_50_L.mp3
    - assets\leftear\hearingTest.online.warble_1000_60_L.mp3
    - assets\leftear\hearingTest.online.warble_1000_70_L.mp3
    - assets\leftear\hearingTest.online.warble_1000_80_L.mp3

    - assets\leftear\hearingTest.online.warble_2000_10_L.mp3
    - assets\leftear\hearingTest.online.warble_2000_20_L.mp3
    - assets\leftear\hearingTest.online.warble_2000_30_L.mp3
    - assets\leftear\hearingTest.online.warble_2000_40_L.mp3
    - assets\leftear\hearingTest.online.warble_2000_50_L.mp3
    - assets\leftear\hearingTest.online.warble_2000_60_L.mp3
    - assets\leftear\hearingTest.online.warble_2000_70_L.mp3
    - assets\leftear\hearingTest.online.warble_2000_80_L.mp3

    - assets\leftear\hearingTest.online.warble_4000_10_L.mp3
    - assets\leftear\hearingTest.online.warble_4000_20_L.mp3
    - assets\leftear\hearingTest.online.warble_4000_30_L.mp3
    - assets\leftear\hearingTest.online.warble_4000_40_L.mp3
    - assets\leftear\hearingTest.online.warble_4000_50_L.mp3
    - assets\leftear\hearingTest.online.warble_4000_60_L.mp3
    - assets\leftear\hearingTest.online.warble_4000_70_L.mp3
    - assets\leftear\hearingTest.online.warble_4000_80_L.mp3

    - assets\leftear\hearingTest.online.warble_8000_10_L.mp3
    - assets\leftear\hearingTest.online.warble_8000_20_L.mp3
    - assets\leftear\hearingTest.online.warble_8000_30_L.mp3
    - assets\leftear\hearingTest.online.warble_8000_40_L.mp3
    - assets\leftear\hearingTest.online.warble_8000_50_L.mp3
    - assets\leftear\hearingTest.online.warble_8000_60_L.mp3
    - assets\leftear\hearingTest.online.warble_8000_70_L.mp3
    - assets\leftear\hearingTest.online.warble_8000_80_L.mp3

    # RIGHT EAR :
    - assets\rightear\hearingTest.online.warble_250_10_R.mp3
    - assets\rightear\hearingTest.online.warble_250_20_R.mp3
    - assets\rightear\hearingTest.online.warble_250_30_R.mp3
    - assets\rightear\hearingTest.online.warble_250_40_R.mp3
    - assets\rightear\hearingTest.online.warble_250_50_R.mp3
    - assets\rightear\hearingTest.online.warble_250_60_R.mp3
    - assets\rightear\hearingTest.online.warble_250_70_R.mp3
    - assets\rightear\hearingTest.online.warble_250_80_R.mp3

    - assets\rightear\hearingTest.online.warble_500_10_R.mp3
    - assets\rightear\hearingTest.online.warble_500_20_R.mp3
    - assets\rightear\hearingTest.online.warble_500_30_R.mp3
    - assets\rightear\hearingTest.online.warble_500_40_R.mp3
    - assets\rightear\hearingTest.online.warble_500_50_R.mp3
    - assets\rightear\hearingTest.online.warble_500_60_R.mp3
    - assets\rightear\hearingTest.online.warble_500_70_R.mp3
    - assets\rightear\hearingTest.online.warble_500_80_R.mp3

    - assets\rightear\hearingTest.online.warble_1000_10_R.mp3
    - assets\rightear\hearingTest.online.warble_1000_20_R.mp3
    - assets\rightear\hearingTest.online.warble_1000_30_R.mp3
    - assets\rightear\hearingTest.online.warble_1000_40_R.mp3
    - assets\rightear\hearingTest.online.warble_1000_50_R.mp3
    - assets\rightear\hearingTest.online.warble_1000_60_R.mp3
    - assets\rightear\hearingTest.online.warble_1000_70_R.mp3
    - assets\rightear\hearingTest.online.warble_1000_80_R.mp3

    - assets\rightear\hearingTest.online.warble_2000_10_R.mp3
    - assets\rightear\hearingTest.online.warble_2000_20_R.mp3
    - assets\rightear\hearingTest.online.warble_2000_30_R.mp3
    - assets\rightear\hearingTest.online.warble_2000_40_R.mp3
    - assets\rightear\hearingTest.online.warble_2000_50_R.mp3
    - assets\rightear\hearingTest.online.warble_2000_60_R.mp3
    - assets\rightear\hearingTest.online.warble_2000_70_R.mp3
    - assets\rightear\hearingTest.online.warble_2000_80_R.mp3

    - assets\rightear\hearingTest.online.warble_4000_10_R.mp3
    - assets\rightear\hearingTest.online.warble_4000_20_R.mp3
    - assets\rightear\hearingTest.online.warble_4000_30_R.mp3
    - assets\rightear\hearingTest.online.warble_4000_40_R.mp3
    - assets\rightear\hearingTest.online.warble_4000_50_R.mp3
    - assets\rightear\hearingTest.online.warble_4000_60_R.mp3
    - assets\rightear\hearingTest.online.warble_4000_70_R.mp3
    - assets\rightear\hearingTest.online.warble_4000_80_R.mp3

    - assets\rightear\hearingTest.online.warble_8000_10_R.mp3
    - assets\rightear\hearingTest.online.warble_8000_20_R.mp3
    - assets\rightear\hearingTest.online.warble_8000_30_R.mp3
    - assets\rightear\hearingTest.online.warble_8000_40_R.mp3
    - assets\rightear\hearingTest.online.warble_8000_50_R.mp3
    - assets\rightear\hearingTest.online.warble_8000_60_R.mp3
    - assets\rightear\hearingTest.online.warble_8000_70_R.mp3
    - assets\rightear\hearingTest.online.warble_8000_80_R.mp3
